"""Build the GitHub-viewable markdown report (old/new images side by side per region).

Usage:
    python tests/build_compare_report.py
"""

from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "output"
OUT_MD = Path(__file__).parent / "compare_report.md"

HEADER = """# Cloud mask comparison: old vs new

Old = production `s2_old_filter` style (`dep_tools.s2_utils.mask_clouds`,
filters `[dilation(3), erosion(2)]`, applied to the combined saturated/defective
+ shadow + medium/high cloud + thin cirrus SCL mask).

New = candidate config: medium+high cloud combined, then
`opening(3) -> closing(3) -> dilation(3)`, unioned with saturated/defective
(no morphology on that class).

Generated by `tests/compare_masks.py --datetime 2025`.
"""


def main() -> None:
    old_files = sorted(OUTPUT_DIR.glob("*_old.png"))
    sections = [HEADER]
    for old_path in old_files:
        name = old_path.stem[: -len("_old")]
        new_path = OUTPUT_DIR / f"{name}_new.png"
        if not new_path.exists():
            continue
        title = name.replace("_", " ").title()
        sections.append(f"""
## {title}

| Old | New |
|---|---|
| ![old](output/{old_path.name}) | ![new](output/{new_path.name}) |
""")

    OUT_MD.write_text("\n".join(sections))
    print(f"wrote {OUT_MD} ({len(sections) - 1} regions)")


if __name__ == "__main__":
    main()
